spring:
  application:
    name: Local Reservation
  datasource:
    url: jdbc:mysql://localhost:3306/local-reservation
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true